name: run-ga
on:
  workflow_dispatch:
    inputs:
      population_size: {type: number, default: 80}
      generations: {type: number, default: 40}
      crossover_prob: {type: number, default: 0.8}
      mutation_prob: {type: number, default: 0.05}

jobs:
  ga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - run: pip install -r requirements.txt
      - name: Patch config
        run: |
          python - <<'PY'
          import yaml,sys
          cfg=yaml.safe_load(open("config.yaml","r",encoding="utf-8"))
          g=cfg["ga"]
          ip = "${{ github.event.inputs.population_size }}"; g["population_size"]=int(float(ip))
          ig = "${{ github.event.inputs.generations }}"; g["generations"]=int(float(ig))
          ic = "${{ github.event.inputs.crossover_prob }}"; g["crossover_prob"]=float(ic)
          im = "${{ github.event.inputs.mutation_prob }}"; g["mutation_prob"]=float(im)
          open("config.yaml","w",encoding="utf-8").write(yaml.safe_dump(cfg,sort_keys=False))
          print("patched",cfg["ga"])
          PY
      - name: Download needed GEO files (cached locally in repo data/raw)
        run: |
          mkdir -p data/raw
          # assume you already committed small files or they exist via actions cache
      - name: Run GA step
        run: python -c "from src.utils import load_cfg; import src.step06_GA_feature_selection as m; c=load_cfg('config.yaml'); print(m.run(c,c['paths']))"
      - name: Export web JSON
        run: python tools/prepare_web.py
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
